name: Family Config - New
description: Create new family config
title: "[New]: "
labels: []

body:
  - type: markdown
    id: intro
    attributes:
      value: |
        Consult https://github.com/RoyaleAPI/cr-api-ux/wiki/Family-Config for detailed description of all the fields. Here are some tips:
  
        - `color`: should be all lower case
        - `key`: will be used in the URL. Convention is to use all lower case
        - `emblem`: do not include the file extension `.png`
        - `description` and `links`: delete the lines if you have none
        - `tag`:  do not include the `#` hash tag with the clan tags
  - type: textarea
    id: config
    attributes:
      label: Family configuration
      description: Provide the full YAML config
      value: Paste your YAML config here
      render: yaml
  - type: textarea
    id: info
    attributes:
      label: Additional Info
      description: Provide additional info if necessary
      value: 
